/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "surface-container": "#e5eeff",
              "on-surface": "#0b1c30",
              "error": "#ba1a1a",
              "on-tertiary-container": "#ffede6",
              "error-container": "#ffdad6",
              "tertiary-container": "#bc4800",
              "on-error": "#ffffff",
              "primary-container": "#2563eb",
              "on-tertiary": "#ffffff",
              "on-error-container": "#93000a",
              "surface-tint": "#0053db",
              "surface-container-lowest": "#ffffff",
              "on-tertiary-fixed-variant": "#7d2d00",
              "surface-container-low": "#eff4ff",
              "surface-container-highest": "#d3e4fe",
              "surface": "#f8f9ff",
              "on-surface-variant": "#434655",
              "surface-bright": "#f8f9ff",
              "primary": "#004ac6",
              "secondary-fixed-dim": "#4edea3",
              "background": "#f8f9ff",
              "on-primary-fixed": "#00174b",
              "on-primary-container": "#eeefff",
              "on-primary": "#ffffff",
              "surface-container-high": "#dce9ff",
              "on-background": "#0b1c30",
              "inverse-on-surface": "#eaf1ff",
              "on-secondary-fixed": "#002113",
              "on-tertiary-fixed": "#360f00",
              "secondary-fixed": "#6ffbbe",
              "secondary": "#006c49",
              "tertiary-fixed": "#ffdbcd",
              "on-secondary-container": "#00714d",
              "surface-variant": "#d3e4fe",
              "secondary-container": "#6cf8bb",
              "outline": "#737686",
              "surface-dim": "#cbdbf5",
              "inverse-primary": "#b4c5ff",
              "primary-fixed": "#dbe1ff",
              "inverse-surface": "#213145",
              "outline-variant": "#c3c6d7",
              "primary-fixed-dim": "#b4c5ff",
              "tertiary-fixed-dim": "#ffb596",
              "tertiary": "#943700",
              "on-secondary-fixed-variant": "#005236",
              "on-secondary": "#ffffff",
              "on-primary-fixed-variant": "#003ea8"
      },
      "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
      },
      "spacing": {
              "stack-md": "0.5rem",
              "stack-lg": "1rem",
              "gutter": "0.75rem",
              "stack-sm": "0.25rem",
              "container-margin": "1rem",
              "stack-xl": "1.5rem"
      },
      "fontFamily": {
              "body-lg": ["Inter", "sans-serif"],
              "label-sm": ["Inter", "sans-serif"],
              "label-md": ["Inter", "sans-serif"],
              "body-md": ["Inter", "sans-serif"],
              "h3": ["Inter", "sans-serif"],
              "h1": ["Inter", "sans-serif"],
              "h2": ["Inter", "sans-serif"]
      },
      "fontSize": {
              "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
              "label-sm": ["11px", {"lineHeight": "14px", "letterSpacing": "0.05em", "fontWeight": "600"}],
              "label-md": ["12px", {"lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "500"}],
              "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
              "h3": ["18px", {"lineHeight": "24px", "fontWeight": "600"}],
              "h1": ["24px", {"lineHeight": "32px", "fontWeight": "700"}],
              "h2": ["20px", {"lineHeight": "28px", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
}
